version : '3'
services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
        
  authservice:
    image: authservicefinal
    build: authenticationservice/
    restart: always
    network_mode: host
    container_name: authServiceCon
    ports:
        - 8084:8084
    depends_on:
      - mysql
      - eurekaServer
      - rabbitmq
    healthcheck:
        test: "exit 0"
      
  userTrackService:
    image: usertrackservicefinal
    build: usertrackservice/
    restart: always
    network_mode: host
    container_name: userTrackCon
    ports:
        - 8085:8085
    depends_on:
      - mongo
      - eurekaServer
      - rabbitmq
    healthcheck:
        test: "exit 0"

  eurekaServer:
    image: triplekdock/eurekaserver:v1
    restart: always
    network_mode: host
    container_name: eurekaServerCon
    ports:
        - 9003:9003 
    healthcheck:
        test: "exit 0"

  zuulService:
    image: triplekdock/zuulserver:v1
    restart: always
    network_mode: host
    container_name: zuulServerCon
    ports:
        - 8086:8086 
    healthcheck:
        test: "exit 0"       

  mysql:
    image: mysql:5.5
    ports:
        - 3306:3306
    container_name: mysql_container
    network_mode: host
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: UserDb
        MYSQL_USER: approot
        MYSQL_PASSWORD: root123


  angular:
    image: frontendfinal
    build: ./
    network_mode: host
    container_name: angular-register
    ports:
        - 8080:8080
    healthcheck:
        test: "exit 0"

  mongo:
    image: mongo:3.2-jessie
    ports:
        - 27017:27017
    container_name: mongo
    network_mode: host
    
    



