version : '3'
services:
  authservice:
    image: triplekdock/authenticationservice:v2
    restart: always
    network_mode: host
    container_name: authServiceCon
    ports:
        - 8084:8084
    depends_on:
      - mysql
      - eurekaServer
      
  userTrackService:
    image: triplekdock/usertrackservice:v2
    restart: always
    network_mode: host
    container_name: userTrackCon
    ports:
        - 8085:8085
    depends_on:
      - mongo
      - eurekaServer

  eurekaServer:
    image: triplekdock/eurekaserver:v1
    restart: always
    network_mode: host
    container_name: eurekaServerCon
    ports:
        - 9003:9003 

  zuulService:
    image: triplekdock/zuulserver:v1
    restart: always
    network_mode: host
    container_name: zuulServerCon
    ports:
        - 8086:8086   

  orchestrationService:
    image: triplekdock/orchestrationservice:v1
    restart: always
    network_mode: host
    container_name: orchestrationServerCon
    ports:
        - 8888:8888
    depends_on:
      - eurekaServer     

  mysql:
    image: mysql:5.5
    ports:
        - 3306:3306
    container_name: mysql_container
    network_mode: host
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: UserDb
        MYSQL_USER: approot
        MYSQL_PASSWORD: root123

  angular:
    image: triplekdock/muzixfrontendauthentication:v2
    network_mode: host
    container_name: angular-register
    ports:
        - 8080:8080

  mongo:
    image: mongo:3.2-jessie
    ports:
        - 27017:27017
    container_name: mongo
    network_mode: host
    
    



